<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Data Form Produsen DG - SIGAP Award 2025</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: 'Arial', sans-serif;
            font-size: 9px;
            line-height: 1.4;
            padding: 15px;
        }
        .header {
            text-align: center;
            margin-bottom: 15px;
            padding-bottom: 10px;
            border-bottom: 2px solid #333;
        }
        .header h1 {
            font-size: 16px;
            margin-bottom: 5px;
            color: #333;
        }
        .header p {
            font-size: 10px;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th {
            background-color: #28a745;
            color: white;
            padding: 6px 4px;
            text-align: left;
            font-size: 8px;
            font-weight: bold;
            border: 1px solid #1e7e34;
        }
        td {
            padding: 5px 4px;
            border: 1px solid #ddd;
            font-size: 8px;
            word-wrap: break-word;
            white-space: normal;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .badge {
            padding: 2px 6px;
            border-radius: 3px;
            font-size: 7px;
            font-weight: bold;
            display: inline-block;
        }
        .badge-success {
            background-color: #28a745;
            color: white;
        }
        .badge-secondary {
            background-color: #6c757d;
            color: white;
        }
        .badge-warning {
            background-color: #ffc107;
            color: #333;
        }
        .text-center {
            text-align: center;
        }
        .footer {
            margin-top: 15px;
            padding-top: 10px;
            border-top: 1px solid #ddd;
            text-align: center;
            font-size: 8px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Data Form Penilaian Produsen Data Geospasial</h1>
        <p>SIGAP Award 2025 - Produsen Data Geospasial Kehutanan</p>
        <p>Tanggal Export: {{ date('d F Y, H:i') }} WIB</p>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 3%;">No</th>
                <th style="width: 18%;">Nama Instansi</th>
                <th style="width: 15%;">Petugas</th>
                <th style="width: 8%;">Nominasi</th>
                <th style="width: 10%;">Telepon</th>
                <th style="width: 10%;">Status</th>
                <th style="width: 8%;">Nilai</th>
                <th style="width: 10%;">Bobot (45%)</th>
                <th style="width: 18%;">Catatan</th>
            </tr>
        </thead>
        <tbody>
            @forelse($forms as $index => $form)
            <tr>
                <td class="text-center">{{ $index + 1 }}</td>
                <td>{{ $form->nama_instansi ?? '-' }}</td>
                <td>{{ $form->nama_petugas ?? '-' }}</td>
                <td class="text-center">
                    @if($form->nominasi)
                        <span class="badge badge-success">Masuk</span>
                    @else
                        <span class="badge badge-secondary">Tidak</span>
                    @endif
                </td>
                <td>{{ $form->phone ?? '-' }}</td>
                <td class="text-center">
                    @php
                        $badgeClass = match($form->status_nilai) {
                            'scored' => 'badge-success',
                            'in_review' => 'badge-warning',
                            default => 'badge-secondary',
                        };
                    @endphp
                    <span class="badge {{ $badgeClass }}">{{ $form->status_label ?? 'Pending' }}</span>
                </td>
                <td class="text-center">{{ $form->total_score ?? '-' }}</td>
                <td class="text-center">{{ $form->nilai_bobot_total !== null ? number_format($form->nilai_bobot_total, 2) : '-' }}</td>
                <td>{{ $form->notes ?? '-' }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="9" class="text-center">Tidak ada data</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>Total Data: {{ $forms->count() }} | Generated by SIGAP Award System</p>
    </div>
</body>
</html>
